### ISSUE TITLE
markdown infrastructure refactor

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1302]
## Tasks

- [x] replace markdoc vs commonmark or similar markdown renderer to increase interop
- [x] table of contents should include "startpage" instead of hardcoded `href` to remove href
- [x] use `slug` instead of `href` to minimize risks of broken links
- [x] use web components with lit.dev to increase interop and reduce maintenance effort
- [x] derive the title from # instead of frontmatter for interop with github and less explanation required
- [x] #1321

**Comment by floriandwt** [comment]
@inlang/docs @samuelstroschein Loom update: https://www.loom.com/share/445129eabba04843b7ffa339b8d85a9e

Hopefully I get this done tomorrow!!! The GFM bug is extremely annoying, I can't really get back to the point were it worked.

### Last tasks before release:
- [ ] Use GFM (currently there is a bug, also experienced by others… seen here: https://github.com/remarkjs/remark-gfm/issues/57)
- [ ] Implement proper styling
- [ ] Proper anchor handling + Copy and usage of toasts inside of the headings
- [ ] Implement advanced marketplace tableOfContents (in the making)

**Comment by floriandwt** [comment]
btw. sanitization is working through perfectly, it is no nice that we can white label not only custom elements but also their attributes!

**Comment by samuelstroschein** [comment]
goob job @floriandwt! i commented on the loom

**Comment by floriandwt** [comment]
Thanks to @samuelstroschein the annoying issue has gone away 😁

<img width="910" alt="Screenshot 2023-09-20 at 11 19 29 PM" src="https://github.com/inlang/monorepo/assets/92092993/88b23acb-08b2-4a97-9718-2bc5365092c0">

such a bad timing, what a coincidence!! Look at the release of the new version of the plugin, haven't considered that to be a realistic case from where the bug could appear (because it worked on Friday :D): 
<img width="811" alt="Screenshot 2023-09-20 at 11 20 47 PM" src="https://github.com/inlang/monorepo/assets/92092993/ae18243d-3ec9-41bb-9686-f9b73b568488">
