### ISSUE TITLE
force absolute path in project settings file path

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1441]
## Problem 

Using relative paths in the settings file gives no guarantee that they are resolved correctly because some apps implicitly rely on . 

```json
{
  "modules": [
    "./source-code/plugin.js"
  ]
}
```

## Proposal

Force an absolute project settings file path in `loadProject`, which enables the SDK to resolve relative paths from the absolute project settings path. 

```diff

const project = await loadProject({
-  settingsFilePath: "./project.inlang.json"
+  settingsFilePath: resolve(cwd + "./project.inlang.json")
})
```

### Tasks 

- [ ] Force absolute paths in project settings file to avoid the dependency on CWD which does not exists in browser environments. 
- [ ] Resolve fs paths from the absolute settings path 
- [ ] write unit test for forcing absolute path settings path in `loadProject`
- [ ] write unit test that verifies if relative fs.readFile, and fs.writeFile are resolved from the absolute settings path

**Comment by felixhaeberle** [comment]
work in #1446
