### ISSUE TITLE
project directory implementation proposal 

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1678]
## Context

- read the directory proposal [here](https://docs.google.com/document/d/1OYyA1wYfQRbIJOIBDliYoWjiUlkFBNxH_U2R4WpVRZ4/edit#heading=h.pecv6xb7ial6)

## Goal

- complete implementation by the end of the week
- no implicit behavior that can lead to unexpected/buggy behavior 
- no breaking behavior for apps

## Tasks

- [x] create a project directory in `loadProject` with a readme that prompts the user to delete the old project.inlang.json file
- [ ] .gitignore .prettierignore files
- [x] add console.warn to `loadProject` if .json is loaded
- [x] throw if a project has no name e.g. `.inlang` 
- [ ] major release of the inlang CLI that throws when `project.inlang.json` is used
- [ ] new prerelease of paraglide js CLI that throws when `project.inlang.json` is used 
- [ ] update docs
- [x] rename `projectSettingsFile` to `projectPath`
- [ ] avoid breaking: ide extension looks for project directory in current working directory (as it does right now with project.inlang.json)
- [ ] avoid breaking: editor looks for project directory in current working directory (avoid breakage and postpone filepicker implementation)
- [ ] add `project.name` property to a project

**Comment by NilsJacobsen** [comment]
I like the Readme migration guide. 👍

**Comment by samuelstroschein** [comment]
implemented via #1762
