### ISSUE TITLE
refactor/remove @inlang/is-valid-js-identifer

### ISSUE THREAD

**Issue by samuelstroschein** [inlang/monorepo#1943]
@LorisSigrist sorry for my approval of #1940. The externalization of `isValidJsIdentifier` broke the monorepo und generally seems unnecessary. The function is called in two places only (after completing the tasks below). Having a dedicated package with published and everything is waaaaay to much effort for sharing 10 lines of logical code [that never breaks] and 30 hardcoded keywords. 

You can decide to keep the package or remove it. If I were in your shoes, I would delete the package. 

---

_Notes on improving PR reviews_ 

- Make fewer changes in one PR. I oversaw the externalization of `isValidJsIdentifier` in those many changes.
- Prompt for feedback on the changes. What exactly should I review? You might have wondered if `dts-buddy` would be OK. Ask :) 

---

## Tasks (if you decide to keep the package)

- [ ] switch to typescript (the codebase uses typescript, not JS with JSDoc)
- [ ] remove dts-buddy for ts compile which is not stable and does not suit the codebase (because made for JS with JSDoc)
- [ ] remove conditional logic (you can always use the escaped version) https://github.com/inlang/monorepo/blob/44fd20bb5e588cbc2086bedd66243e27b67d7f19/inlang/source-code/paraglide/paraglide-js/src/compiler/paramsType.ts#L23-L29
- [ ] remove conditional logic (you can always use the escaped version) https://github.com/inlang/monorepo/blob/44fd20bb5e588cbc2086bedd66243e27b67d7f19/inlang/source-code/paraglide/paraglide-js/src/compiler/compilePattern.ts#L26-L31

**Comment by LorisSigrist** [comment]
Sure! I did ask Felix before externalising the package, but I can remove it. I can see how externalising such a small amount of code wouldn't be worth it.
